# Generated by Django 4.0 on 2022-06-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(max_length=150)),
                ('degree', models.CharField(max_length=150)),
                ('year', models.DateField()),
            ],
        ),
    ]
