# Generated by Django 4.0 on 2022-06-16 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_education_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='year',
            new_name='startYear',
        ),
    ]
