# Generated by Django 4.0 on 2022-06-16 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_rename_year_education_startyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='endYear',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2999)]),
        ),
    ]
