# Generated by Django 4.0.6 on 2022-07-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_skill_icon_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon_html',
            field=models.CharField(default='fa-solid fa-question', max_length=200),
        ),
    ]
